name: alphafold1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-tidyverse
  - r-ranger
  - r-xgboost
  - r-venndiagram
  - r-optparse
  - r-proc
  - r-readxl
  - r-caret
  - biopython
  - r-essentials
  - r-data.table
  - r-proc
  - networkx
  - numpy
  - r-readxl
  - pandas
  - r-base
  - snakemake
  - biopandas
  - r-r.utils
  - tabix
  - r-gridextra
