---
 pdb_dir: "data/pdb_files/"
 feature_folder: "tools/feature/feature-3.1.0/"
 dssp_bin: "tools/dssp/mkdssp" 
# xcat: mkdssp
 dssp_dir: "tools/dssp/"
# xcat: mkdssp
 protinter_bin: "tools/protinter/protinter_mod2" 
 alphafold_download_adress: "https://ftp.ebi.ac.uk/pub/databases/alphafold/latest/UP000005640_9606_HUMAN_v2.tar"
 dbNSFP_download_adress: "ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFP4.2a.zip"
 short_partition: "short"
 long_partition: "long"
 
