---
 pdb_dir: "results/pdb_files/"
 feature_folder: "tools/feature/feature-3.1.0/"
 dssp_bin: "mkdssp" 
 dssp_dir: "tools/dssp/"
 protinter_bin: "tools/protinter/protinter" 
 alphafold_download_adress: "https://ftp.ebi.ac.uk/pub/databases/alphafold/v2/UP000005640_9606_HUMAN_v2.tar"
 dbNSFP_download_adress: "ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFP4.2a.zip"
 short_partition: "short"
 long_partition: "long"
 clinvar_link: "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/archive_2.0/2022/clinvar_20220109.vcf.gz"
 
